# State machine update frequency (Hz)
loop_frequency: 50

# Lab bounds (m)
lab_bounds: [9, 9, 3]

# Distance threshold for reaching a desired position
dist_thres: 0.3

# Desired positions in 3D space
pos:
  takeoff_z: 1
  start:   [-2, -1, 1]
  goal:    [-2, -1, 1]
  land:    [-2, -1, 1]

use_takeoff_as_start: true

# Usage of external planner and/or controller during mission execution phase
use_external_controller: true

# Print debug information
enable_debug: true
