define: &max_vel 0.5
define: &max_acc 0.5

sdf_map:
  resolution: 0.1
  map_size_x: 5
  map_size_y: 5
  map_size_z: 1.7
  obstacles_inflation: 0.199
  local_bound_inflate: 0.5
  local_map_margin: 50
  ground_height: -0.2
  default_dist: 0.0
  p_hit: 0.68
  p_miss: 0.4
  p_min: 0.12
  p_max: 0.99
  p_occ: 0.7
  min_ray_length: 0.5
  max_ray_length: 3
  virtual_ceil_height: -10
  optimistic: false
  signed_dist: false
  box_min_x: -2.5
  box_min_y: -2.5
  box_min_z:  -0.2
  box_max_x: 2.5
  box_max_y: 2.5
  box_max_z: 1.5

map_ros:         # Gazebo        # Intel realsense 4255  
  cx: 422.86578  # 424.50000     # 422.86578  
  cy: 242.46154  # 240.50000     # 242.46154
  fx: 427.75729  # 454.68577     # 427.75729
  fy: 427.75729  # 454.68577     # 427.75729
  depth_filter_maxdist: 3
  depth_filter_mindist: 0.2
  depth_filter_margin: 2
  k_depth_scaling_factor: 1000.0
  skip_pixel: 2
  esdf_slice_height: 0.3
  visualization_truncate_height: 10.09
  visualization_truncate_low: -2.0
  show_occ_time: false
  show_esdf_time: false
  show_all_map: true
  frame_id: world

fsm:
  thresh_replan1: 0.5
  thresh_replan2: 0.5
  thresh_replan3: 1.5
  replan_time: 0.200

exploration:
  refine_local: true
  refined_num: 7
  refined_radius: 5.0
  max_decay: 0.8
  top_view_num: 15
  vm: *max_vel
  am: *max_acc
  
  # Cost to change yaw angle 
  # this should ideally be matched closely with the controller's maximum yaw rate, but might need to be more conservative because of noise and delays
  yd:  0.7     # "$(eval 45 * 3.1415926 / 180.0)"   DONT LOWER THIS BELOW 0.6 in hardware flights. DRONE GIVES UP
  ydd: 1.5707963     # "$(eval 90 * 3.1415926 / 180.0)"  not used
  
  # Cost to change velocity vector direction
  # higher values resist changes and act more sluggish but result in better, stable movements
  # lower values decrease flight times but with poor mapping
  w_dir: 3 
  tsp_dir: "$(find lkh_tsp_solver)/resource" # YAML limitation: needs to be remapped from outside if you want relative paths. 
  relax_time: 1.0

frontier:
  cluster_min: 100
  cluster_size_xy: 1.5
  cluster_size_z: 10.0
  min_candidate_dist: 0.5  # minimum distance a viewpoint needs to be from the centroid of a frontier to be considered
  min_candidate_clearance: 0.21
  candidate_dphi: 0.261799383  # "$(eval 15 * 3.1415926 / 180.0)"
  candidate_rnum: 3
  candidate_rmin: 0.75
  candidate_rmax: 1.75
  down_sample: 3
  min_visib_num: 10
  
  # % change that must happen for the frontier to call for recompute
  # Low values mean that we moved along very fast across the space, considering even a small changed to be enough to reevaluate
  # high values mean we are more strict. We make a lot of observations before moving. This is sluggish but makes the environment scene more stable
  min_view_finish_fraction: 0.5    

perception_utils:
  top_angle: 0.56125
  left_angle: 0.69222
  right_angle: 0.68901
  max_dist: 3
  vis_dist: 1.0


# UNUSED
# heading_planner:
#   yaw_diff: 0.523598767 # "$(eval 30 * 3.1415926 / 180.0)"
#   half_vert_num: 5
#   lambda1: 2.0
#   lambda2: 1.0
#   max_yaw_rate: 0.174532922 # "$(eval 10 * 3.1415926 / 180.0)"
#   w: 20000.0
#   weight_type: 1

manager:
  max_vel: *max_vel
  max_acc: *max_acc
  max_jerk: 4
  dynamic_environment: 0
  local_segment_length: 6.0
  clearance_threshold: 0.2
  control_points_distance: 0.35
  use_geometric_path: true
  use_kinodynamic_path: true
  use_topo_path: true
  use_optimization: true
  use_active_perception: true
  min_time: true
  max_yawdot: 0.7  # 60 * 3,1415926 / 180,0
  relax_time1: 0.3
  relax_time2: 1.5

search:
  max_tau: 0.8
  init_max_tau: 1.0
  max_vel: *max_vel
  vel_margin: 0.25
  max_acc: *max_acc
  w_time: 10.0
  horizon: 5.0
  lambda_heu: 10.0
  resolution_astar: 0.025
  time_resolution: 0.8
  margin: 0.2
  allocate_num: 100000
  check_num: 10
  optimistic: false

astar:
  lambda_heu: 10000.0
  resolution_astar: 0.2
  allocate_num: 1000000
  max_search_time: 0.001

optimization:
  ld_smooth: 20.0
  ld_dist: 10.0
  ld_feasi: 2.0
  ld_start: 100.0
  ld_end: 0.5
  ld_guide: 1.5
  ld_waypt: 0.3
  ld_view: 0.0
  ld_time: 1.0
  dist0: 0.7
  max_vel: *max_vel
  max_acc: *max_acc
  algorithm1: 15
  algorithm2: 11
  max_iteration_num1: 2
  max_iteration_num2: 2000
  max_iteration_num3: 200
  max_iteration_num4: 200
  max_iteration_time1: 0.0001
  max_iteration_time2: 0.005
  max_iteration_time3: 0.003
  max_iteration_time4: 0.003
  bspline:
    limit_vel: *max_vel
    limit_acc: *max_acc
    limit_ratio: 1.1
