perception:
  attention_map:
    2d:
      # gazebo
      low_H: 80
      # low_S: 120
      # low_V: 100

      # high_H: 170
      # high_S: 255
      # high_V: 255


      # low_H: 50
      low_S: 120
      low_V: 80

      high_H: 130
      high_S: 255
      high_V: 255

    3d:
      att_min: 1 # lower cutoff for attention values. Keep higher if you want more spread
      
      # rate at which attention values decay. Keep higher if you want slower decay. 
      # Might need to be tuned with att_min to keep spread constant
      diffusion_factor: 0.99

      # rate for semantic map update
      # lower value means slower update, less confident, more robust to fast movements
      learning_rate: 0.5